# Generated by Django 2.2 on 2022-08-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0007_auto_20220725_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
